version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: demodb 

  fastapi:
    build: backend
    ports: 
      - 8000:8000
    depends_on:
      - "mongo"

